# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Note' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Note
  pod 'CocoaLumberjack/Swift', '~> 3.5.3'

  target 'NoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
